# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: grpc/payment.proto for package 'payment'

require 'grpc'
require 'grpc/payment_pb'

module Payment
  module PaymentService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'payment.PaymentService'

      rpc :ProcessPayment, ::Payment::PaymentRequest, ::Payment::PaymentResponse
    end

    Stub = Service.rpc_stub_class
  end
end
