# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc/payment.proto

require 'google/protobuf'


descriptor_data = "\n\x12grpc/payment.proto\x12\x07payment\"_\n\x0ePaymentRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x13\n\x0b\x63ustomer_id\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x02\x12\x16\n\x0epayment_method\x18\x04 \x01(\t\"J\n\x0fPaymentResponse\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t2U\n\x0ePaymentService\x12\x43\n\x0eProcessPayment\x12\x17.payment.PaymentRequest\x1a\x18.payment.PaymentResponseb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Payment
  PaymentRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("payment.PaymentRequest").msgclass
  PaymentResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("payment.PaymentResponse").msgclass
end
